# Generated by Django 5.2.10 on 2026-01-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='moltiplicator',
            field=models.IntegerField(default=1),
        ),
    ]
